### ISSUE TITLE
How to use wait_time?

### ISSUE THREAD

**Issue by stlxiii** [SvenskaSpel/har2locust#21]
This is very likely a comprehension issue on my part, but har2locust generates a class with a single task. What is the correct way to utilize the wait_time attribute in this situation?  My understanding is that it doesn't do anything.

In my main file, all_tests.py, I run the scenarios I record like this:

```
class Test__e2e_complete_timesheet(HttpUser):
    host = variables.get('url')
    
    weight          = 50
    tasks           = [e2e_complete_timesheet.t,]
    
    def on_start(self):
        self.client.variables = variables
        self.client.verify = False
```

**Comment by cyberw** [comment]
wait_time is executed after each task run regardless of how many tasks there are in a User/TaskSet. 

(if you’re ”borrowing” the task and adding it to a separate User like in your example, the wait time of *your* User (Test__e2e_complete_timesheet) will get used)

**Comment by stlxiii** [comment]
But the recording (.har) gets converted to one single task, correct?  So wait_time doesn't do anything unless I split the single task into several.  I've tried that, but they seem to run concurrently instead of one after the other.

**Comment by cyberw** [comment]
Well. Wait time does exactly what I said, it waits _between_ task runs, regardless of the number of tasks in a user. 

Tasks within a single User instance dont run concurrently, because each user instance only runs a single greenlet (think "thread" if you dont know what that is) and cannot ever run two lines of code at the same time :)

**Comment by cyberw** [comment]
What _might_ have you confused, I guess, is the fact that tasks are not _ordered_, every time a task has finished, the User just picks one at random.

**Comment by stlxiii** [comment]
Thanks, that helps me understand the behavior, I had assumed tasks were sequential. 

But if I need operations to be done in a certain order, say 1-login, 2-test and 3-logout, with each of these tasks containing multiple calls.  That means I need to group all of this inside a single task, and the only way to have a wait time is to use time.sleep manually after each call?

**Comment by cyberw** [comment]
yes, easiest is just to group them within a single task. If you want to make things complicated, you _can_ use SequentialTaskSet to accomplish the same thing https://docs.locust.io/en/stable/tasksets.html#sequentialtaskset-class

**Comment by stlxiii** [comment]
Thanks for your help! It makes sense in my head now :)
